steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - "docker pull gcr.io/calcium-vector-326722/webapp:latest || exit 0"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/calcium-vector-326722/webapp"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "flaskappml"
      - "--image"
      - "gcr.io/calcium-vector-326722/webapp:latest"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
